### ISSUE TITLE
Auto-launching discovery service fails after clean install

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#369]
# Bug Report

After installing MeasurementLink on a clean system, running a Python measurement service fails.

## Repro or Code Sample

- Reimage PC
- Install MeasurementLink and drivers
- Do not run InstrumentStudio or MeasurementLink UI Editor
- Install Python, Poetry, etc.
- Run a Python measurement service

## Expected Behavior

The Python measurement service starts the MeasurementLink discovery service.

## Current Behavior

The Python measurement service starts the MeasurementLink discovery service (visible in Task Manager), but it also raises an unhandled exception:
```
PS D:\dev\measurementlink-python\examples\sample_measurement> poetry run python .\measurement.py -v
2023-09-06 13:52:04,696 INFO: Measurement service hosted on port: 52461
2023-09-06 13:52:04,723 ERROR: Error in registering with discovery service.
Traceback (most recent call last):
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 128, in register_measurement_service
    register_response = self.stub.RegisterService(request)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 85, in stub
    address = _get_discovery_service_address()
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 223, in _get_discovery_service_address
    _ensure_discovery_service_started(key_file_path)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 237, in _ensure_discovery_service_started
    _discovery_service_subprocess = _start_service(exe_file_path, key_file_path)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 284, in _start_service
    with _open_key_file(str(key_file_path)) as _:
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 335, in _open_key_file
    win32_file_handle = win32file.CreateFile(
pywintypes.error: (3, 'CreateFile', 'The system cannot find the path specified.')
Traceback (most recent call last):
  File "D:\dev\measurementlink-python\examples\sample_measurement\measurement.py", line 115, in <module>
    main()
  File "D:\dev\measurementlink-python\examples\sample_measurement\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\dev\measurementlink-python\examples\sample_measurement\.venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\dev\measurementlink-python\examples\sample_measurement\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\dev\measurementlink-python\examples\sample_measurement\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\dev\measurementlink-python\examples\sample_measurement\measurement.py", line 110, in main
    with sample_measurement_service.host_service():
  File "D:\dev\measurementlink-python\ni_measurementlink_service\measurement\service.py", line 396, in host_service
    self.grpc_service.start(
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\service_manager.py", line 109, in start
    self.discovery_client.register_measurement_service(port, service_info, measurement_info)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 128, in register_measurement_service
    register_response = self.stub.RegisterService(request)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 85, in stub
    address = _get_discovery_service_address()
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 223, in _get_discovery_service_address
    _ensure_discovery_service_started(key_file_path)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 237, in _ensure_discovery_service_started
    _discovery_service_subprocess = _start_service(exe_file_path, key_file_path)
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 284, in _start_service
    with _open_key_file(str(key_file_path)) as _:
  File "D:\dev\measurementlink-python\ni_measurementlink_service\_internal\discovery_client.py", line 335, in _open_key_file
    win32_file_handle = win32file.CreateFile(
pywintypes.error: (3, 'CreateFile', 'The system cannot find the path specified.')
```

## Workaround

Run it again.

## Your Environment

* OS & Device: Windows
* `ni-measurementlink-service` version: 1.2.0-dev2 from main
* MeasurementLink version: 23.8.0d578
* Python version: 3.9.13

[AB#2514643](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2514643)

**Comment by bkeryan** [comment]
[`_open_key_file`](https://github.com/ni/measurementlink-python/blob/main/ni_measurementlink_service/_internal/discovery_client.py) catches `ERROR_FILE_NOT_FOUND` (2) and translates it to `FileNotFoundError`, but the clean install use case is generating `ERROR_PATH_NOT_FOUND` (3). 

`_start_service` catches `IOError`, which is a deprecated alias for `OSError`.

`pywintypes.error` is not a subclass of `OSError`. There is a bug report but it has been open for over 10 years: [pywintypes.error should inherit from WindowsError #486](https://www.github.com/mhammond/pywin32/issues/486)

I think it makes sense to do the following:
- Update `_open_key_file` to translate `ERROR_PATH_NOT_FOUND` to `FileNotFoundError`.
- Update `_start_service` to catch `OSError`.

**Comment by bkeryan** [comment]
Tested with a clean install of MeasurementLink and commit 8fa8137ec256d2cccb8c23013d9efcc5782706c4
